[package]
name = "simlar"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
pyo3 = { version = "0.28.0", features = ["extension-module"] }
rayon = "1"

[build-dependencies]
pyo3-build-config = "0.28.0"
